import type { Metadata } from "next";
import "./globals.css";
import { Mulish, Roboto } from 'next/font/google';

export const metadata: Metadata = {
  title: "Car Dealer App",
  description: "Generated by create next app",
};

const mulish = Mulish({
  weight: "variable",
  subsets: ['latin'],
  variable: "--font-heading",
  display: "swap"
})

const roboto = Roboto({
  weight: "400",
  subsets: ['latin'],
  variable: "--font-body",
  display: "swap"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
